# Generated by Django 3.0 on 2019-12-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
